# This file was generated by GoReleaser. DO NOT EDIT.
cask "amanmcp" do
  name "amanmcp"
  desc "Local-first RAG MCP server for AI coding assistants"
  homepage "https://github.com/Aman-CERP/amanmcp"
  version "0.11.0-rc4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amanmcp"

  on_macos do
    on_arm do
      url "https://github.com/Aman-CERP/amanmcp/releases/download/v#{version}/amanmcp_#{version}_darwin_arm64.tar.gz"
      sha256 "c1cad0cfe2010fecf4ffb6d22a239435bb7eea70668230893dc0afa8c07620ff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amanmcp"]
    end
  end

  caveats do
    "To get started:"
    "  cd your-project"
    "  amanmcp"
  end

  # No zap stanza required
end
