# This file was generated by GoReleaser. DO NOT EDIT.
cask "amanmcp" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "3429adfd82982fa81399121a51139592216909c0eb0d64364c776a0dfe07b4c2"
      url "https://github.com/Aman-CERP/amanmcp/releases/download/v#{version}/amanmcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "amanmcp"
  desc "Local-first RAG MCP server for AI coding assistants"
  homepage "https://github.com/Aman-CERP/amanmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amanmcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amanmcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started:
      cd your-project
      amanmcp
  EOS
end
