# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amanmcp < Formula
  desc "Local-first RAG MCP server for AI coding assistants"
  homepage "https://github.com/Aman-CERP/amanmcp-raw"
  version "0.2.3"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Aman-CERP/amanmcp-raw/releases/download/v0.2.3/amanmcp_0.2.3_darwin_arm64.tar.gz"
    sha256 "9350503f180f11870ec9e60dd2d68367532e4d026b369c0fbd81a602ed97ee70"

    def install
      bin.install "amanmcp"
    end
  end

  def caveats
    <<~EOS
      To get started:
        cd your-project
        amanmcp
    EOS
  end

  test do
    system "#{bin}/amanmcp", "version"
  end
end
